version: '2'
services:
  subastion:
    build:
      context: .
      dockerfile: Dockerfile.subastion
      args:
        aws_access_key: changewithbuildarg
        aws_secret_key: changewithbuildarg
        aws_kms_key_id: changewithbuildarg
        aws_kms_alias: "orchestration"
        aws_region: "ca-central-1"
        aws_zones: '["ca-central-1a", "ca-central-1b"]'
        aws_build_nat: "false"
        vault_addr: "https://vault:8200"
        vault_cacert_file: terraform/modules/dockervault/vault.cert.pem
    cap_add:
      - IPC_LOCK
    stdin_open: true 
    tty: true        

networks:
  default:
    name: subastion
